// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject1
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProject1PackageString = "a4308b57-1142-42cf-b4bf-750f2a799c8e";
        public static Guid guidVSIXProject1Package = new Guid(guidVSIXProject1PackageString);

        public const string guidVSIXProject1PackageCmdSetString = "9b52ab9b-da1e-4333-9137-fa054164578d";
        public static Guid guidVSIXProject1PackageCmdSet = new Guid(guidVSIXProject1PackageCmdSetString);

        public const string guidImagesString = "a5964e60-8d5f-493c-9433-75355a614ee7";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}